### ISSUE TITLE
can not apply for more than one voucher

### ISSUE THREAD

**Issue by khaledyoussef24** [codescalers/cloud4students#135]
## Describe the bug

after applying for voucher the field is disabled and can't add more vouchers

## To Reproduce

    1. Go to profile
    2. insert voucher and click on apply for voucher
    3. the field is disabled if you have one more voucher you can not use it
![image](https://user-images.githubusercontent.com/110984055/229837676-7c362311-2fdc-4222-8be7-6920eb76e975.png)

**Comment by rawdaGastan** [comment]
you need to use all your vms and public ips then apply for a new voucher :D

**Comment by khaledyoussef24** [comment]
now I have one vm token but I want to make a k8s with one worker or a medium vm
but i can not redeem another voucher to increase my tokens from 1 to 2.
so i will have to go through and make a small vm then finish my tokens first.
