### ISSUE TITLE
terms and conditions are in spanish

### ISSUE THREAD

**Issue by khaledyoussef24** [codescalers/cloud4students#157]
## Describe the bug

terms and conditions are in spanish
![Screenshot from 2023-04-06 11-19-27](https://user-images.githubusercontent.com/110984055/230337872-b9687a53-2890-4e26-8520-2ce269a2681d.png)

**Comment by rawdaGastan** [comment]
@ehab-hassan can you help in it?

**Comment by rawdaGastan** [comment]
https://docs.google.com/document/d/1JYPxOrzl5BdmViDuU6oF8PYdNEeJCdYt7GINa4VCMUk/edit

as @xmonader mentioned
