### ISSUE TITLE
warnings of validations while signing in

### ISSUE THREAD

**Issue by khaledyoussef24** [codescalers/cloud4students#159]
## Describe the bug

validations gives warning while filling the fields in sign in
![Screenshot from 2023-04-06 10-44-44](https://user-images.githubusercontent.com/110984055/230343174-4381cf4d-89ab-4799-a766-80a499a54a24.png)

**Comment by maayarosama** [comment]
Already fixed, you need to pull development

**Comment by xmonader** [comment]
closed by the fixes of #174
