### ISSUE TITLE
apply for voucher page is misleading

### ISSUE THREAD

**Issue by xmonader** [codescalers/cloud4students#168]
![image](https://user-images.githubusercontent.com/64129/230377252-dfa7bd79-2035-4e59-af9c-b2e649776194.png)

i click on apply for voucher, i get redirected to account settings to apply a voucher not request a new voucher
![image](https://user-images.githubusercontent.com/64129/230377409-1af5d615-c162-4e1d-99da-81a748edc088.png)

**Comment by rawdaGastan** [comment]
I suggest to open the modal once we redirect the user
