### ISSUE TITLE
add quota

### ISSUE THREAD

**Issue by rawdaGastan** [codescalers/cloud4students#25]
- add quota in profile settings to show the count of vms and kuberentes the user user has
- hide vms and k8s tabs if quota is 0 (vms = 0 and publiv_ips = 0)
- user should know how quota is calculated (1 vm for small instance, 2 for medium, 3 for large) and 1 public IP for each used public IP

**Comment by samaradel** [comment]
https://www.figma.com/file/5wo9b6Sik1J0z4eLf0CHzB/Untitled?node-id=0-1&t=QYgdeJ1fZA0gh3xR-0

**Comment by samaradel** [comment]
@rawdaGastan there're 3 options, please confirm
