### ISSUE TITLE
add 404 page

### ISSUE THREAD

**Issue by xmonader** [codescalers/cloud4students#334]
accessing a page like `/aaaa` doesn't show a 404 page

![image](https://github.com/codescalers/cloud4students/assets/64129/a6c49666-256e-48ca-9d31-0a5f8556ad16)

**Comment by ehab-hassan** [comment]
![image](https://github.com/codescalers/cloud4students/assets/10484295/64f4e177-fc66-4ffb-866b-953b55e39298)
![404_codescalers2](https://github.com/codescalers/cloud4students/assets/10484295/a12976cd-722a-4d4c-8aa7-cb354420e711)
https://www.figma.com/file/da9QInhria3pF8wqIM0rcY/404-Page?type=design&node-id=16-2&t=VK8Fabcc2AEGEn60-0

**Comment by xmonader** [comment]
Looks great!!
