### ISSUE TITLE
how to handle kubernetes quota

### ISSUE THREAD

**Issue by xmonader** [codescalers/cloud4students#48]
it's not clear yet the meaning of the kubernetes quota, does it represent the number of vms in a cluster? if so should we just use the vms quota? or should we treat it as number of vms that can be part of kubernetes clusters?? or is it meant to be for number of the clusters the user can create? and if so.. for how many workers?

**Comment by samaradel** [comment]
we have some suggestions here [#25](https://github.com/rawdaGastan/cloud4students/issues/25)

**Comment by AbdelrahmanElawady** [comment]
remove k8s quota, only vms.
k8s node = vm
