### ISSUE TITLE
Verification code not sent 

### ISSUE THREAD

**Issue by Nayer-Sobhy** [codescalers/cloud4students#541]
## Describe the bug

when a new user is trying to signup, after finishing the registration, they dont get the verification code

## To Reproduce
go to https://c4s.codescalers-egypt.com/login
then click sign up 
you will be redirected to https://c4s.codescalers-egypt.com/signup (create a new account page) 
after filling the info and clicking on create an account 
the user should get a verification code but they didnt 

## Expected behavior

the user should get the verification code to complete the creation of the account

**Comment by xmonader** [comment]
Emails are supposed to be queued for delivery, escalated to ops to review account's activity

**Comment by rawdaGastan** [comment]
Issue has been solved
