### ISSUE TITLE
Add a page to display next launch in c4s

### ISSUE THREAD

**Issue by rawdaGastan** [codescalers/cloud4students#579]
- Add an endpoint to enable/disable the page
- Don't allow any user to access the service while this page is enabled
- Admins can enable/disable from UI
- Admins only can access the service if the page is enabled

**Comment by rowangamal** [comment]
- Add endpoint to Get state of next launch
- Enable signin page (for all) from UI, even if state is true (next-launch)

**Comment by rowangamal** [comment]
Add the update feature in frontend.
- A button in the admin page that allows to `enable/disable` `next launch`
