### ISSUE TITLE
Top nav is always visible even when user isn't logged in

### ISSUE THREAD

**Issue by maayarosama** [codescalers/cloud4students#76]
## Describe the bug

Top nav is always visible even when user isn't logged in

## Expected behavior

It should only be visible when user is logged in
## Screenshots

![top-menu](https://user-images.githubusercontent.com/66883096/227779729-02266060-18e4-4c3e-9815-f14a0e3e0e3e.png)

**Comment by zaelgohary** [comment]
I found this been done [here](https://github.com/codescalers/cloud4students/blob/8ad20af9a178e5f32e69fcaf014e1ca212823b61/client/src/App.vue)
